camera_url: "http://192.168.10.153/webcam/?action=snapshot"

moonraker_url: "http://127.0.0.1:7125"

check_interval: 5
consecutive_failures: 3
on_failure: "pause"

ssim_threshold: 0.97   # try 0.97–0.99. Lower = less sensitive

log_path: "/tmp/klipper-pfd.log"
